# -*- mode: ruby -*-
# vi: set ft=ruby :

boxfile = ARGV[ARGV.length-1] # naively assume last argument is box

# This is a generic Vagrant configuration that allows launching
# a virtual machine from a box file. This is not useful to do
# anything except for maintaining base boxes incrementally without
# having to keep VMs alive and eating disk-space in VirtualBox.
Vagrant.configure("2") do |config|
  config.vm.define "#{boxfile}" do |basebox|
    basebox.vm.box = "#{boxfile}.box"

    basebox.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
      vb.name = boxfile
    end

    # since we launch a base box to maintain it as a base box...
    basebox.winssh.insert_key = false
    basebox.ssh.insert_key = false
  end
end
