- name: Install nginx and avahi to serve locally built documentation
  apt:
    name: ['nginx', 'avahi-daemon']
    state: present
  tags:
    - packages

- name: Make nginx serve correct directory
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: ^\s+root.*
    line: "        root /home/vagrant;"
  notify: restart nginx

- name: Turn on auto-indexing
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: ^\s+try_files.*
    line: "                 autoindex on;"
  notify: restart nginx
