- name: Install nginx and avahi to serve locally built documentation
  apt:
    name: ['nginx', 'avahi-daemon']
    state: present
  tags:
    - packages

- name: Make nginx serve correct directory
  shell: sed -i 's/root.*/root \/home\/vagrant;/' /etc/nginx/sites-available/default
  notify: restart nginx
