- name: Enable EPEL repository
  yum:
    name:
      - epel-release
    state: present

- name: Install build tools
  yum:
    name:
      - gcc-toolset-9-gcc
      - gcc-toolset-9-gcc-c++
      - ninja-build
      - perl-core
    enablerepo: PowerTools
    state: present

- name: Select gcc 9
  command: echo ". /opt/rh/gcc-toolset-9/enable" >> /home/vagrant/.bashrc
