$settings[:aws_boxes] ||= []
$settings[:aws_boxes] << "tqtc/macos-aws"

Vagrant.configure('2') do |config|
    config.vm.guest = :darwin
    config.vm.provider :aws
    config.vm.provider :aws do |aws, override|
        aws.ami = "ami-0e985ceaa52d29eda" # macOS Monterey 12.1
        # macOS can only be run on dedicated hosts
        aws.instance_type = "mac1.metal"
        aws.tenancy = "host"
    end
end
