$settings[:aws_boxes] ||= []
$settings[:aws_boxes] << "tqtc/macos-aws"

Vagrant.configure('2') do |config|
    config.vm.guest = :darwin
    config.vm.provider :aws
    config.vm.provider :aws do |aws, override|
        aws.ami = "ami-0e985ceaa52d29eda" # macOS Monterey 12.1

        # macOS can only be run on dedicated hosts
        aws.instance_type = "mac1.metal"
        aws.tenancy = "host"

        # Use userdata to bootstrap the machine with the vagrant user and the key pair.
        # The lstrip is needed for the shebang to work.
        aws.user_data = <<-BASH.lstrip
            #!/bin/bash
            # output from this script will be in /var/log/amazon/ec2/ec2-macos-init.log
            echo "Provisioning user vagrant with passwordless sudo"
            sysadminctl -addUser vagrant -password "#{ENV['AWS_VM_ADMIN_PASSWORD']}" -admin -home /Users/vagrant
            createhomedir -c -u vagrant
            touch /etc/sudoers.d/vagrant
            echo 'vagrant ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant
            chown -R vagrant /Users/vagrant

            echo "Starting and configuring SSH"
            # make sure the SSH server is running
            systemsetup -f -setremotelogin on

            mkdir -p /Users/vagrant/.ssh
            echo "#{$settings[:aws][:public_key]}" > /Users/vagrant/.ssh/authorized_keys
            chown -R vagrant /Users/vagrant/.ssh

            echo "Enabling screen sharing"
            # try to enable screen sharing (experimental)
            sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
                -activate -configure -access -off -restart -agent -privs -all -allowAccessFor -allUsers

            # make vagrant owner of /usr/local so that brew doesn't complain
            echo "Fixing homebrew permissions"
            sudo chown -R vagrant /usr/local

            echo "Finished startup provisioning"

            # at the very end, delete the default user
            sysadminctl -deleteUser ec2-User
        BASH
    end
end
