#!/usr/bin/env bash

source=$(readlink $0)
if [[ $source == "" ]]; then
  if [[ $WINDIR != "" ]]; then
    source=$(realpath $0)
  else
    echo "This script expects to be run via a symlink!"
    exit 1
  fi
fi

minicoin_dir=$(dirname $source)
project_dir="$PWD"
[[ -z $MINICOIN_PROJECT_DIR ]] && export MINICOIN_PROJECT_DIR="$PWD"
cd $minicoin_dir

function update_minicoin()
{
  git fetch --all --tags 2> /dev/null > /dev/null
  if [ $? == 0 ]; then
    if [ "$1" == "" ]; then
      minicoin_version=`git tag --list --sort=-taggerdate | head -n1`
    else
      minicoin_version=$1
    fi
  else
    >&2 echo "Failed to fetch tags, can't update minicoin!"
  fi
  if [ ! -z "$minicoin_version" ]; then
    echo "Checking out version $minicoin_version"
    git stash > /dev/null
    output=`git checkout $minicoin_version 2>&1`
    error=$?
    if [ $error -gt 0 ]; then
      >&2 echo "$output"
    fi
    git checkout master -- ../setup.sh minicoin
  fi
  return $?
}

function show_help()
{
  cat help.txt
}

if [ "$1" == "update" ]; then
  shift
  update_minicoin "$@"
  error=$?
elif [[ "$1" == "help" && "$2" == "" ]]; then
  show_help
  error=0
else
  vagrant "$@"
  error=$?
fi

cd "$project_dir"
exit $error
