$settings[:aws_boxes] ||= []
$settings[:aws_boxes] << "tqtc/windows-aws"

Vagrant.configure('2') do |config|
    config.vm.guest = :windows
    config.vm.provider :aws
    config.vm.provider :aws do |aws, override|
        # Microsoft Windows Server 2019 Base
        aws.ami = "ami-00a452e228b12f42b"
        # 8 vCPU, 32 GB RAM
        aws.instance_type = "t2.2xlarge"
        # we need more disk space
        aws.block_device_mapping = [{
            "DeviceName" => "/dev/sda1",
            "Ebs.VolumeSize" => 50
        }]
    end
end
