Vagrant.configure('2') do |config|
    config.vm.guest = :windows
    config.vm.provider :azure
    config.vm.provider :azure do |azure, override|
        azure.vm_image_urn = 'MicrosoftWindowsServer:WindowsServer:datacenter-core-20h2-with-containers-smalldisk:latest'
    end
end
