- name: build and test machine
  hosts: all
  become: yes

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  roles:
    - base
    - build
    - test-server
