$settings[:aws_boxes] ||= []
$settings[:aws_boxes] << "minicoin/linux-cloud"

Vagrant.configure('2') do |config|
    config.vm.guest = :linux
    config.vm.provider :aws
    config.vm.provider :aws do |aws, override|
        # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
        aws.ami = "ami-0d2a4a5d69e46ea0b"
        # 8 vCPU, 32 GB RAM
        aws.instance_type = "t2.2xlarge"
    end
end
