- block:
    - include_vars:
        file: redhat.yml
    - import_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- block:
    - include_vars:
        file: debian.yml
    - import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
