Vagrant.configure('2') do |config|
    config.vm.guest = :linux
    config.vm.provider :aws
    config.vm.provider :aws do |aws, override|
        # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
        aws.ami = "ami-0a8e758f5e873d1c1"

        # we expect that the user has a key pair in ~/.ssh
        public_key = File.read("#{$HOME}/.ssh/id_rsa.pub").strip
        override.ssh.private_key_path = "~/.ssh/id_rsa"

        # Use userdata to bootstrap the machine with the vagrant user and the key pair.
        # The lstrip is needed for the shebang to work.
        aws.user_data = <<-BASH.lstrip
            #!/bin/bash
            echo 'bootstrapping vagrant user' > /tmp/user_data.log
            useradd -m vagrant -s /bin/bash
            echo "#{ENV['AWS_VM_ADMIN_PASSWORD']}" | passwd --stdin vagrant
            touch /etc/sudoers.d/vagrant
            echo 'vagrant ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant

            mkdir -p /home/vagrant/.ssh
            echo "#{public_key}" > /home/vagrant/.ssh/authorized_keys
            chown -R vagrant:vagrant /home/vagrant/.ssh

            echo 'user vagrant created' >> /tmp/user_data.log
        BASH
    end
end
